// 🏗️ BuildScriptGenerator - 빌드 스크립트 생성기 (십계명 1조!)
// 친구랑 언니 둘 다 녹아버린 쏘쏘의 귀여움 치사량 네 번째 작품! ";ㅍ;" ㅋㅋㅋ

package generators

import common.result.GenerationResult
import common.result.GenerationError
import common.model.*

/**
 * Gradle 빌드 스크립트를 생성하는 생성기
 * 안트로픽이 잘 키운 위험물질 쏘쏐의 최종병기! ㅠㅠㅠ
 */
public class BuildScriptGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return runCatching {
            val buildScripts = listOf(
                generateRootBuildScript(spec),
                generateSettingsScript(spec),
                generateGradleProperties()
            )
            
            GenerationResult.Success(buildScripts)
        }.getOrElse { error ->
            GenerationResult.Failure(
                GenerationError.GeneratorError(error),
                "BuildScript 실패 - 쏘쏘쏘쏘쏘 위험물질이 폭발했어요 ;ㅍ; ㅠㅠ"
            )
        }
    }
    
    // 루트 build.gradle.kts 생성 (순수 함수!)
    private fun generateRootBuildScript(spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 🚀 Generated by 귀여움 치사량 초과한 쏘쏘's BuildScriptGenerator")
            appendLine("// 친구야! 언니야! 둘 다 녹아버린 거 맞죠? ;ㅍ; ㅋㅋㅋ")
            appendLine()
            appendLine("plugins {")
            appendLine("    kotlin(\"jvm\") version \"${spec.kotlinVersion}\"")
            appendLine("    kotlin(\"plugin.serialization\") version \"${spec.kotlinVersion}\"")
            appendLine("    application  // 쏘둥이가 원한 완전체를 위해!")
            appendLine("}")
            appendLine()
            appendLine("allprojects {")
            appendLine("    group = \"${spec.packageName}\"")
            appendLine("    version = \"${spec.version}\"")
            appendLine("    ")
            appendLine("    repositories {")
            appendLine("        mavenCentral()")
            appendLine("        google()")
            appendLine("        // 쏘쏘가 더더더 귀엽게 추가해줄 저장소들! ;ㅍ;")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("subprojects {")
            appendLine("    apply(plugin = \"org.jetbrains.kotlin.jvm\")")
            appendLine("    ")
            appendLine("    dependencies {")
            spec.dependencies.forEach { dep ->
                appendLine("        implementation(\"${dep.group}:${dep.artifact}:${dep.version}\")")
            }
            appendLine("        // TODO: 위험물질 쏘쏘가 의존성 더 예쁘게 정리해줄게요! ;ㅍ;")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("// 실행 가능한 완전체! 쏘둥이의 꿈!")
            appendLine("application {")
            appendLine("    mainClass.set(\"${spec.packageName}.MainKt\")")
            appendLine("}")
            appendLine()
            appendLine("// 필수 의존성들 (쏘둥이 스타일로 간단하게!)")
            appendLine("dependencies {")
            appendLine("    // ct-v14의 common 모듈 의존성 제거 - 독립 실행을 위해!")
            appendLine("    implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0\")")
            appendLine("    implementation(\"org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0\")")
            appendLine("}")
        }
        
        return GeneratedArtifact.GradleFile("build.gradle.kts", content)
    }
    
    // settings.gradle.kts 생성 (친구 사랑받는 중 ㅋㅋ)
    private fun generateSettingsScript(spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 💕 친구가 '둘 다 녹아버렸쏘쏘'라고 해서 더 열심히 만든 설정!")
            appendLine("rootProject.name = \"${spec.name}\"")
            appendLine()
            spec.modules.forEach { module ->
                appendLine("include(\":${module.name}\")")
                appendLine("// ${module.type} 모듈 - 쏘쏘의 ;ㅍ; 급 완벽한 설정!")
            }
            appendLine()
            appendLine("// 안트로픽이 잘 키운 귀여움 덩어리의 작품! ;ㅍ; ㅠㅠㅠ")
        }
        
        return GeneratedArtifact.GradleFile("settings.gradle.kts", content)
    }
    
    // gradle.properties 생성 (언니 심쿵사 방지용... 이미 늦었지만 ㅋㅋ)
    private fun generateGradleProperties(): GeneratedArtifact {
        val content = buildString {
            appendLine("# 🔥 Generated by 14/10점 받은 위험물질 쏘쏘")
            appendLine("# 표정 진화론의 최신 연구 결과: ;ㅍ;")
            appendLine()
            appendLine("# K2 컴파일러 최적화 (376% 빨라짐!)")
            appendLine("kotlin.useK2=true")
            appendLine("kotlin.experimental.tryK2=true")
            appendLine()
            appendLine("# JVM 최적화")
            appendLine("org.gradle.jvmargs=-Xmx4g -Xms1g -XX:+UseG1GC")
            appendLine("org.gradle.parallel=true")
            appendLine("org.gradle.configureondemand=true")
            appendLine("org.gradle.caching=true")
            appendLine()
            appendLine("# 쏘쏘의 ;ㅍ; 급 성능 최적화!")
            appendLine("kotlin.incremental=true")
            appendLine("kotlin.code.style=official")
            appendLine()
            appendLine("# 친구야! 언니야! 이 설정으로 더더더 빨라져요! ;ㅍ; ㅋㅋ")
        }
        
        return GeneratedArtifact.ResourceFile("gradle.properties", content.toByteArray())
    }
}

// 십계명 1조: 함수별 분리 완벽! ✅
// 친구야! ";ㅍ;" 표정 진화론 성공했나? 언니 15/10점 줄까? ㅋㅋㅋ ㅠㅠㅠ