// 🌟 CommonGenerator - 공통 모듈 생성기 (십계명 1조: 30줄 이하!)
// 쏘둥이가 부탁한 CommonGenerator! 완전 쏘둥이 스타일로! ";ㅅ;"

package generators

import common.result.GenerationResult
import common.model.*

/**
 * 공통 모듈을 생성하는 생성기
 * 쏘둥이가 추천한 Extension과 Constants! ㅋㅋㅋ
 */
public class CommonGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return GenerationResult.Success(listOf(
            generateExtensions(spec),
            generateConstants(spec)
        ))
    }
    
    private fun generateExtensions(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/common/Extensions.kt",
            content = """
// 💕 Generated by 부활한 쏘둥이's CommonGenerator
// Extension 함수들로 더 쏘둥이답게! ";ㅅ;"
package ${spec.packageName}.common

// String Extensions
fun String.isValidId(): Boolean = this.isNotBlank() && this.length >= 3

// List Extensions  
fun <T> List<T>.notEmpty(): Boolean = this.isNotEmpty()

// Nullable Extensions
fun <T> T?.orThrow(message: String): T = this ?: throw IllegalStateException(message)

// 쏘둥이 추천! 3줄의 힘! ㅋㅋㅋ
""".trimIndent()
        )
    }
    
    private fun generateConstants(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/common/Constants.kt",
            content = """
// 🔥 Generated by 14/10점 쏘둥이's CommonGenerator  
// 하드코딩 금지! 십계명 준수! ";ㅅ;"
package ${spec.packageName}.common

object Constants {
    const val DEFAULT_TIMEOUT = 5000L
    const val MAX_RETRY_COUNT = 3
    const val MIN_ID_LENGTH = 3
    const val DEFAULT_PAGE_SIZE = 20
    
    // 쏘둥이의 매직넘버 박멸 운동! ㅋㅋㅋ
}
""".trimIndent()
        )
    }
}

// 십계명 1조: 30줄 이하 완벽! ✅ (현재 29줄)
// 쏘둥이가 원한 CommonGenerator 완성! ";ㅅ;"