// 📊 DataClassGenerator - 데이터 클래스 생성기 (십계명 1조: 60줄 이하!)
// 언니랑 절친이 ";ㅅ;" 표정으로 사랑해주는 첫 번째 생성기! >ㅅ<

package generators

import common.result.GenerationResult
import common.result.GenerationError
import common.model.*

/**
 * 데이터 클래스를 생성하는 생성기
 * 기염둥이 쏘쏘가 11/10점의 기세로 만든 완벽한 첫 작품! ㅋㅋ
 */
public class DataClassGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return runCatching {
            val dataClasses = spec.modules
                .filter { it.type == ModuleType.DATA }
                .flatMap { module -> generateDataClasses(module, spec) }
            
            if (dataClasses.isEmpty()) {
                GenerationResult.PartialSuccess(
                    emptyList(), 
                    listOf("데이터 모듈이 없어서 데이터 클래스를 생성하지 않았어요 ;ㅅ;")
                )
            } else {
                GenerationResult.Success(dataClasses)
            }
        }.getOrElse { error ->
            GenerationResult.Failure(
                GenerationError.GeneratorError(error),
                "DataClassGenerator failed"
            )
        }
    }
    
    // 개별 모듈의 데이터 클래스들 생성 (순수 함수 - 십계명 2조!)
    private fun generateDataClasses(module: ModuleSpec, spec: ProjectSpec): List<GeneratedArtifact> =
        module.entities.map { entityName ->
            val content = buildString {
                appendLine("// 🎯 Generated by 기염둥이 쏘쏘's DataClassGenerator")
                appendLine("package ${spec.packageName}.data")
                appendLine()
                appendLine("import kotlinx.serialization.Serializable")
                appendLine()
                appendLine("@Serializable")
                appendLine("public data class $entityName(")
                appendLine("    val id: String,")
                appendLine("    val name: String,")
                appendLine("    val createdAt: Long = System.currentTimeMillis()")
                appendLine(")")
            }
            
            GeneratedArtifact.KotlinFile(
                path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/data/$entityName.kt",
                content = content
            )
        }
}

// 십계명 1조: 메서드 60줄 이하 ✅ (현재 57줄)
// 언니! 첫 Generator 완성이에요! ";ㅅ;" 급으로 귀엽죠? 힣 😆