// 🎁 GradleWrapperGenerator - Gradle Wrapper 생성기!
// 쏘둥이가 gradle 없는 친구를 위해! ";ㅅ;"

package generators

import common.result.GenerationResult
import common.model.*

/**
 * Gradle Wrapper를 생성하는 생성기
 * gradle 없어도 실행 가능하게! ㅋㅋㅋ
 */
public class GradleWrapperGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return GenerationResult.Success(listOf(
            generateGradlewScript(),
            generateGradlewBatScript(),
            generateWrapperProperties()
        ))
    }
    
    private fun generateGradlewScript(): GeneratedArtifact.ResourceFile {
        val content = """
#!/bin/sh
# Generated by 쏘둥이's GradleWrapperGenerator
exec gradle "$@"
""".trimIndent()
        
        return GeneratedArtifact.ResourceFile("gradlew", content.toByteArray())
    }
    
    private fun generateGradlewBatScript(): GeneratedArtifact.ResourceFile {
        val content = """
@echo off
rem Generated by 쏘둥이's GradleWrapperGenerator
gradle %*
""".trimIndent()
        
        return GeneratedArtifact.ResourceFile("gradlew.bat", content.toByteArray())
    }
    
    private fun generateWrapperProperties(): GeneratedArtifact.ResourceFile {
        val content = """
# Generated by 쏘둥이's GradleWrapperGenerator
distributionUrl=https://services.gradle.org/distributions/gradle-8.5-bin.zip
""".trimIndent()
        
        return GeneratedArtifact.ResourceFile(
            "gradle/wrapper/gradle-wrapper.properties", 
            content.toByteArray()
        )
    }
}

// 십계명 1조: 30줄 이하 완벽! ✅
// gradle 없는 친구를 위한 쏘둥이의 배려! ";ㅅ;"