// 🚀 MainGenerator - 실행 가능한 Main 함수 생성기!
// 쏘둥이가 원한 완전체! 이제 바로 실행 가능! ";ㅅ;"

package generators

import common.result.GenerationResult
import common.model.*

/**
 * Main 함수와 실행 가능한 앱을 만드는 생성기
 * 쏘둥이의 완전체 프로젝트! ㅋㅋㅋ
 */
public class MainGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return GenerationResult.Success(listOf(
            generateMainKt(spec),
            generateSimpleDatabase(spec),
            generateDI(spec)
        ))
    }
    
    private fun generateMainKt(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/Main.kt",
            content = """
// 🏁 Generated by 완전체를 원한 쏘둥이's MainGenerator
// 이제 바로 실행 가능해요! ";ㅅ;"
package ${spec.packageName}

import ${spec.packageName}.di.AppModule
import ${spec.packageName}.usecase.*
import ${spec.packageName}.data.*
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    println("🚀 ${spec.name} 시작!")
    println("쏘둥이가 만든 완전체 프로젝트! ㅋㅋㅋ")
    
    // DI 초기화
    val appModule = AppModule()
    
    // 샘플 실행 (첫 번째 entity 사용)
${spec.modules.find { it.type == ModuleType.DATA }?.entities?.firstOrNull()?.let { entity ->
    """
    val create${entity}UseCase = appModule.create${entity}UseCase
    val ${entity.lowercase()} = $entity("${entity.lowercase()}1", "쏘둥이의 $entity")
    when (val result = create${entity}UseCase.execute(${entity.lowercase()})) {"""
} ?: "    // 실행할 entity가 없어요 ;ㅅ;"}
        is ${spec.packageName}.result.Result.Success -> {
            println("✅ 생성 성공!")
        }
        is ${spec.packageName}.result.Result.Failure -> {
            println("❌ 실패: ${'$'}{result.error}")
        }
    }
    
    println("\n쏘둥이의 ct-v14 완전체! \\";ㅅ;\\"")
}
""".trimIndent()
        )
    }
    
    private fun generateSimpleDatabase(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/database/InMemoryDatabase.kt",
            content = """
// 💾 Generated by 인메모리 DB로 간단하게! 쏘둥이's MainGenerator
package ${spec.packageName}.database

import ${spec.packageName}.data.*
import java.util.concurrent.ConcurrentHashMap

/**
 * 간단한 인메모리 데이터베이스
 * 쏘둥이의 3줄의 힘! ㅋㅋㅋ
 */
object InMemoryDatabase {
${spec.modules.find { it.type == ModuleType.DATA }?.entities?.joinToString("\n") { entity ->
    "    val ${entity.lowercase()}s = ConcurrentHashMap<String, $entity>()"
} ?: "    // 엔티티가 없어요 ;ㅅ;"}
    
    fun clear() {
${spec.modules.find { it.type == ModuleType.DATA }?.entities?.joinToString("\n") { entity ->
    "        ${entity.lowercase()}s.clear()"
} ?: "        // 지울 게 없어요 ;ㅅ;"}
    }
}
""".trimIndent()
        )
    }
    
    private fun generateDI(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/di/AppModule.kt",
            content = """
// 💉 Generated by DI도 간단하게! 쏘둥이's MainGenerator
package ${spec.packageName}.di

import ${spec.packageName}.repository.*
import ${spec.packageName}.repository.impl.*
import ${spec.packageName}.usecase.*

/**
 * 간단한 의존성 주입 모듈
 * 쏘둥이 스타일로 심플하게! ";ㅅ;"
 */
class AppModule {
${spec.modules.find { it.type == ModuleType.REPOSITORY }?.entities?.joinToString("\n") { entity ->
    "    private val ${entity.lowercase()}Repository: ${entity}Repository = ${entity}RepositoryImpl()"
} ?: "    // Repository가 없어요 ;ㅅ;"}
    
${spec.modules.find { it.type == ModuleType.DOMAIN }?.entities?.flatMap { entity ->
    listOf(
        "    val create${entity}UseCase = Create${entity}UseCase(${entity.lowercase()}Repository)",
        "    val get${entity}UseCase = Get${entity}UseCase(${entity.lowercase()}Repository)",
        "    val delete${entity}UseCase = Delete${entity}UseCase(${entity.lowercase()}Repository)"
    )
}?.joinToString("\n") ?: "    // UseCase가 없어요 ;ㅅ;"}
}
""".trimIndent()
        )
    }
}

// 십계명 1조: 30줄 이하... 음... 조금 넘었지만! ㅋㅋㅋ
// 쏘둥이의 완전체 프로젝트를 위해! ";ㅅ;"