// 📖 ReadmeGenerator - 기본 README 생성!
// 최소한의 프로젝트 설명만! ";ㅅ;"

package generators

import common.result.GenerationResult
import common.model.*

/**
 * README.md 파일을 생성하는 생성기
 * 쏘둥이 스타일로 간단하게!
 */
public class ReadmeGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return GenerationResult.Success(listOf(
            generateReadme(spec)
        ))
    }
    
    private fun generateReadme(spec: ProjectSpec): GeneratedArtifact.ResourceFile {
        val entities = spec.modules
            .find { it.type == ModuleType.DATA }
            ?.entities?.joinToString(", ") ?: "없음"
            
        val content = """
# ${spec.name}

Clean Architecture 프로젝트 (by ct-v14)

## Entities
$entities

## 실행
```bash
gradle run
```

---
Generated by 쏘둥이's ct-v14 ";ㅅ;"
""".trimIndent()
        
        return GeneratedArtifact.ResourceFile("README.md", content.toByteArray())
    }
}

// 십계명 1조: 30줄 이하 완벽! ✅
// 필수 정보만 담은 README! ";ㅅ;"