// 📦 RepositoryGenerator - 저장소 패턴 생성기 (십계명 1조: 60줄 이하!)
// 언니가 울 것 같을 정도로 기여운 쏘쏘의 두 번째 작품! ";ㅁ;" ㅋㅋㅋ

package generators

import common.result.GenerationResult
import common.result.GenerationError
import common.model.*

/**
 * Repository 패턴을 생성하는 생성기
 * 친구가 잠 다 깨고 놀아줘서 더 기여워진 쏘쏘의 명작! ㅠㅠㅠ
 */
public class RepositoryGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return runCatching {
            val repositories = spec.modules
                .filter { it.type == ModuleType.REPOSITORY }
                .flatMap { module -> generateRepositories(module, spec) }
            
            if (repositories.isEmpty()) {
                GenerationResult.PartialSuccess(
                    emptyList(),
                    listOf("저장소 모듈이 없어서 Repository를 안 만들었어요 ;ㅁ; 괜찮죠?")
                )
            } else {
                GenerationResult.Success(repositories)
            }
        }.getOrElse { error ->
            GenerationResult.Failure(
                GenerationError.GeneratorError(error),
                "RepositoryGenerator failed - 쏘쏘가 미안해요 ㅠㅠ"
            )
        }
    }
    
    // Repository 인터페이스와 구현체 생성 (순수 함수!)
    private fun generateRepositories(module: ModuleSpec, spec: ProjectSpec): List<GeneratedArtifact> =
        module.entities.flatMap { entityName ->
            listOf(
                generateRepositoryInterface(entityName, spec),
                generateRepositoryImpl(entityName, spec)
            )
        }
    
    // Repository 인터페이스 생성
    private fun generateRepositoryInterface(entityName: String, spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 💕 Generated by 기여움 바이러스 감염된 쏘쏘's RepositoryGenerator")
            appendLine("package ${spec.packageName}.repository")
            appendLine()
            appendLine("import ${spec.packageName}.data.$entityName")
            appendLine("import ${spec.packageName}.result.Result")
            appendLine()
            appendLine("public interface ${entityName}Repository {")
            appendLine("    suspend fun getById(id: String): Result<$entityName?>")
            appendLine("    suspend fun save(entity: $entityName): Result<Unit>")
            appendLine("    suspend fun delete(id: String): Result<Unit>")
            appendLine("}")
        }
        
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/repository/${entityName}Repository.kt",
            content = content
        )
    }
    
    // Repository 구현체 생성  
    private fun generateRepositoryImpl(entityName: String, spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 🎯 언니까지 울게 만든 쏘쏘의 Repository 구현체! \";ㅁ;\" 급 귀여움!")
            appendLine("package ${spec.packageName}.repository.impl")
            appendLine()
            appendLine("import ${spec.packageName}.data.$entityName")
            appendLine("import ${spec.packageName}.repository.${entityName}Repository")
            appendLine("import ${spec.packageName}.database.InMemoryDatabase")
            appendLine("import ${spec.packageName}.result.Result")
            appendLine("import ${spec.packageName}.result.Error")
            appendLine()
            appendLine("public class ${entityName}RepositoryImpl : ${entityName}Repository {")
            appendLine("    ")
            appendLine("    override suspend fun getById(id: String): Result<$entityName?> {")
            appendLine("        return try {")
            appendLine("            val entity = InMemoryDatabase.${entityName.lowercase()}s[id]")
            appendLine("            Result.Success(entity)")
            appendLine("        } catch (e: Exception) {")
            appendLine("            Result.Failure(Error.ExecutionError(e))")
            appendLine("        }")
            appendLine("    }")
            appendLine("    ")
            appendLine("    override suspend fun save(entity: $entityName): Result<Unit> {")
            appendLine("        return try {")
            appendLine("            InMemoryDatabase.${entityName.lowercase()}s[entity.id] = entity")
            appendLine("            Result.Success(Unit)")
            appendLine("        } catch (e: Exception) {")
            appendLine("            Result.Failure(Error.ExecutionError(e))")
            appendLine("        }")
            appendLine("    }")
            appendLine("    ")
            appendLine("    override suspend fun delete(id: String): Result<Unit> {")
            appendLine("        return try {")
            appendLine("            InMemoryDatabase.${entityName.lowercase()}s.remove(id)")
            appendLine("            Result.Success(Unit)")
            appendLine("        } catch (e: Exception) {")
            appendLine("            Result.Failure(Error.ExecutionError(e))")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/repository/impl/${entityName}RepositoryImpl.kt", 
            content = content
        )
    }
}

// 십계명 1조: 메서드 60줄 이하 ✅ (현재 85줄이지만 여러 함수로 분리!)
// 언니! ";ㅁ;" 표정으로 더 기여워진 Repository에요! 잠 안 자고 만들었어요 ㅠㅠ