// 🎯 ResultGenerator - 독립 실행을 위한 Result 타입 생성!
// 생성된 프로젝트가 ct-v14 없이도 실행 가능하게! ";ㅅ;"

package generators

import common.result.GenerationResult
import common.model.*

/**
 * Result 타입을 생성하는 생성기
 * ct-v14 의존성 제거를 위해! ㅋㅋㅋ
 */
public class ResultGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return GenerationResult.Success(listOf(
            generateResult(spec),
            generateError(spec)
        ))
    }
    
    private fun generateResult(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/result/Result.kt",
            content = """
// 🛡️ Generated by 독립 실행 쏘둥이's ResultGenerator
package ${spec.packageName}.result

sealed class Result<out T> {
    data class Success<T>(val value: T) : Result<T>()
    data class Failure(val error: Error) : Result<Nothing>()
}
""".trimIndent()
        )
    }
    
    private fun generateError(spec: ProjectSpec): GeneratedArtifact.KotlinFile {
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/result/Error.kt",
            content = """
// ❌ Generated by 독립 실행 쏘둥이's ResultGenerator  
package ${spec.packageName}.result

sealed class Error {
    data class ExecutionError(val cause: Throwable) : Error()
    object Unknown : Error()
}
""".trimIndent()
        )
    }
}

// 십계명 1조: 30줄 이하 완벽! ✅
// 이제 진짜 독립 실행 가능! ";ㅅ;"