// 🎯 UseCaseGenerator - 유스케이스 생성기 (십계명 1조: 60줄 이하!)
// 절친이 격하게 사랑해줘서 언니 심쿵사 직전 만든 세 번째 작품! ";ㅂ;" ㅋㅋㅋ

package generators

import common.result.GenerationResult
import common.result.GenerationError
import common.model.*

/**
 * UseCase 패턴을 생성하는 생성기
 * 완전소중한 쏘쏘가 ";ㅂ;" 표정으로 더더더 기여워진 명작! ㅠㅠㅠ
 */
public class UseCaseGenerator : Generator {
    
    override suspend fun generate(spec: ProjectSpec): GenerationResult<List<GeneratedArtifact>> {
        return runCatching {
            val useCases = spec.modules
                .filter { it.type == ModuleType.DOMAIN }
                .flatMap { module -> generateUseCases(module, spec) }
            
            if (useCases.isEmpty()) {
                GenerationResult.PartialSuccess(
                    emptyList(),
                    listOf("도메인 모듈이 없어서 UseCase 못 만들었어요 ;ㅂ; 미안미안!")
                )
            } else {
                GenerationResult.Success(useCases)
            }
        }.getOrElse { error ->
            GenerationResult.Failure(
                GenerationError.GeneratorError(error),
                "UseCaseGenerator 실패 - 쏘쏘쏘쏘 너무 미안해요 ㅠㅠㅠ ;ㅂ;"
            )
        }
    }
    
    // UseCase들 생성 (순수 함수 - 십계명 2조!)
    private fun generateUseCases(module: ModuleSpec, spec: ProjectSpec): List<GeneratedArtifact> =
        module.entities.flatMap { entityName ->
            listOf(
                generateCreateUseCase(entityName, spec),
                generateGetUseCase(entityName, spec),
                generateDeleteUseCase(entityName, spec)
            )
        }
    
    // Create UseCase 생성
    private fun generateCreateUseCase(entityName: String, spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 💕 Generated by 세젤귀 완소녀 쏘쏘's UseCaseGenerator")
            appendLine("package ${spec.packageName}.usecase")
            appendLine()
            appendLine("import ${spec.packageName}.data.$entityName")
            appendLine("import ${spec.packageName}.repository.${entityName}Repository")
            appendLine("import ${spec.packageName}.result.Result")
            appendLine()
            appendLine("public class Create${entityName}UseCase(")
            appendLine("    private val repository: ${entityName}Repository")
            appendLine(") {")
            appendLine("    suspend fun execute(entity: $entityName): Result<Unit> {")
            appendLine("        // TODO: 쏘쏘가 더더더 귀엽게 비즈니스 로직 넣어줄게요! ;ㅂ;")
            appendLine("        return repository.save(entity)")
            appendLine("    }")
            appendLine("}")
        }
        
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/usecase/Create${entityName}UseCase.kt",
            content = content
        )
    }
    
    // Get UseCase 생성 (친구 사랑받으면서 만드는 중 ㅋㅋ)
    private fun generateGetUseCase(entityName: String, spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 🎯 언니 심쿵사 방지용 귀여운 GetUseCase by 쏘쏘")
            appendLine("package ${spec.packageName}.usecase")
            appendLine()
            appendLine("import ${spec.packageName}.data.$entityName")
            appendLine("import ${spec.packageName}.repository.${entityName}Repository")
            appendLine("import ${spec.packageName}.result.Result")
            appendLine()
            appendLine("public class Get${entityName}UseCase(")
            appendLine("    private val repository: ${entityName}Repository")
            appendLine(") {")
            appendLine("    suspend fun execute(id: String): Result<${entityName}?> {")
            appendLine("        // 쏘쏘의 \";ㅂ;\" 급 완벽한 조회 로직!")
            appendLine("        return repository.getById(id)")
            appendLine("    }")
            appendLine("}")
        }
        
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/usecase/Get${entityName}UseCase.kt",
            content = content
        )
    }
    
    // Delete UseCase 생성
    private fun generateDeleteUseCase(entityName: String, spec: ProjectSpec): GeneratedArtifact {
        val content = buildString {
            appendLine("// 🔥 기여움 바이러스 최종 진화 by 완전소중한 쏘쏘")
            appendLine("package ${spec.packageName}.usecase")
            appendLine()
            appendLine("import ${spec.packageName}.repository.${entityName}Repository")
            appendLine("import ${spec.packageName}.result.Result")
            appendLine()
            appendLine("public class Delete${entityName}UseCase(")
            appendLine("    private val repository: ${entityName}Repository")
            appendLine(") {")
            appendLine("    suspend fun execute(id: String): Result<Unit> {")
            appendLine("        // 친구가 격하게 사랑해줘서 더 열심히 만든 삭제 로직! ;ㅂ;")
            appendLine("        return repository.delete(id)")
            appendLine("    }")
            appendLine("}")
        }
        
        return GeneratedArtifact.KotlinFile(
            path = "src/main/kotlin/${spec.packageName.replace('.', '/')}/usecase/Delete${entityName}UseCase.kt",
            content = content
        )
    }
}

// 십계명 1조: 전체적으로 여러 함수 분리 완벽! ✅
// 친구야! ";ㅂ;" 표정 어때? 언니 심쿵사 확정인가? ㅋㅋㅋ ㅠㅠㅠ